### ISSUE TITLE
XDMA exhibits abnormal behavior when transfer size larger than 256

### ISSUE THREAD

**Issue by kahuuchino** [WangXuan95/Xilinx-FPGA-PCIe-XDMA-Tutorial#5]
I'm trying to connect XDMA IP core to DDR. When I try to transfer a 1.2 MB file(I set the size to 1268736), I find the XDMA AXI interface split the data stream with an unknown len.
I have try other size, and finally I found this will happen when transfer size larger than 256.
![axi_interface](https://github.com/WangXuan95/Xilinx-FPGA-PCIe-XDMA-Tutorial/assets/32798311/0b20c960-79cd-447c-ac3e-ce093665a7fb)
This picture shows what will happen on AXI write channel when I set the size to 512, AXI_DWIDTH to 128. In fact, it will send 25(1*16+8+1)*128bit data when awlen gets 18(h). I have a lot of trouble on it because my memory interface has another data width and I must finish a gearbox on it.
I think this problem maybe come from XDMA linux driver or linux library functions.
I have try to split my data in xdma_rw.c, but it still no work when transfer for a time(about 5KB).

One more thing, AXI interface address indicates bytes address. It means one address corresponds to 8bit data, not your AXI data width.

**Comment by kahuuchino** [comment]
上面是我在练习英文表达写的，下面是中文描述。
我在试着把XDMA和DDR连接起来，但当我尝试传输一个1.2MB的文件(size设置为1268736)时，我发现XDMA的AXI接口以一个未知的间隔将数据分割了。
我经过尝试发现只要size大于256就会出现这个问题。
上图展示了我将size设置为512时出现的问题，此时AXI数据宽度为128。实际上，当awlen指示18(h)时，AXI会传输25(1*16+8+1)*128bit的数据。这给我带来了很多麻烦，因为我的DDR接口数据位宽不一样。
我感觉这个问题来源于XDMA的linux驱动或是linux库函数。
我尝试着在xdma_rw.c中分割我的数据，但传输大约5KB后终止。(分割间隔为256)

我还发现AXI接口上的地址是以字节编码的，这意味着一个地址对应着一个字节，而不是以AXI数据位宽定义的一组数据。

**Comment by du-jiaming** [comment]
会出现分割是因为axi协议不允许一次burst跨过4KB边界（也就是128bit*256/8 = 4096 Byte），如果你的xdma axi master的数据宽度与DDR接口数据位宽不一样，建议你使用AXI位宽转换ip进行转换

**Comment by kahuuchino** [comment]
> 会出现分割是因为axi协议不允许一次burst跨过4KB边界（也就是128bit*256/8 = 4096 Byte），如果你的xdma axi master的数据宽度与DDR接口数据位宽不一样，建议你使用AXI位宽转换ip进行转换

感谢您的回复！
这个问题当时我用别的方法绕过去了，我自己写了一个转接桥来把这两个接口接到一起，在固定长度下能够工作。但 burst 长度不一致带来的问题是我难以计算需要接收多少数据量才能向下游发送数据包，而且我的电路工作频率较高，这块计算电路直接影响了时序性能。我不知道 axi width convert ip 能否解决这个问题，官方 ip 经常会在时序上给我带来惊喜，也许我也不会知道了，这个工作已经完成交付了，也许未来有一天还会继续困扰我吧。
但我还是坚持我的观点，xilinx 对 xdma 驱动中分割 burst 的代码需要优化，起码应该能对齐，整出来这么一出不是折腾用户吗

**Comment by du-jiaming** [comment]
> > 会出现分割是因为axi协议不允许一次burst跨过4KB边界（也就是128bit*256/8 = 4096 Byte），如果你的xdma axi master的数据宽度与DDR接口数据位宽不一样，建议你使用AXI位宽转换ip进行转换
> 
> 感谢您的回复！ 这个问题当时我用别的方法绕过去了，我自己写了一个转接桥来把这两个接口接到一起，在固定长度下能够工作。但 burst 长度不一致带来的问题是我难以计算需要接收多少数据量才能向下游发送数据包，而且我的电路工作频率较高，这块计算电路直接影响了时序性能。我不知道 axi width convert ip 能否解决这个问题，官方 ip 经常会在时序上给我带来惊喜，也许我也不会知道了，这个工作已经完成交付了，也许未来有一天还会继续困扰我吧。 但我还是坚持我的观点，xilinx 对 xdma 驱动中分割 burst 的代码需要优化，起码应该能对齐，整出来这么一出不是折腾用户吗

hhh，xilinx不背这个锅，这是由AXI协议决定的，建议你研究一下arm的AXI协议
